# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3443fff3f888b0801f9e1a1ff6f43d5a2d3f6fb9c6936de35ba441fa5332c35c9c75a2be92f6d6995acb43d2b372f7075b26a3fd2d489a73a6c56dc1a2f078ad

test:
  secret_key_base: 297faf5ce4447db7f8559ddc42452472bc4d8ee367af036b0239279dd7bd44c15ad0263c106eeb4b289035293a00715f29377527ce67e2b4a92d7926142e8619

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
